# Generated by Django 6.0.1 on 2026-02-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddraft',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saveddraft',
            name='summary_line',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
