# Generated by Django 6.0.1 on 2026-02-02 10:53

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[profiles.models.validate_resume_size]),
        ),
    ]
